server:
  port: 8080


spring:
  application:
    name: api-gateway



  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"


      routes:
        - id: staff-service
          uri: lb://staff-service
          predicates:
            - Path=/teacher/**, /role/**
          filters:
            - AuthenticationFilter

        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**, /category/**, /activity/**, /class/**, /club/**, /house/**, /section/**
          filters:
            - AuthenticationFilter

        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**, /admin/**
          filters:
            - AuthenticationFilter

        - id: student-fee
          uri: lb://student-fee
          predicates:
            - Path=/fee/**
          filters:
            - AuthenticationFilter

        - id: event-manager
          uri: lb://event-manager
          predicates:
            - Path=/events/**
          filters:
            - AuthenticationFilter

        - id: library-management
          uri: lb://library-management
          predicates:
            - Path=/author/**, /books/**, /genres/**, /member/**, /transactions/**
          filters:
            - AuthenticationFilter

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultzone: http://localhost:8761/eureka


logging:
  level:
    io.netty: DEBUG

