spring:
  application:
    name: student-service

eureka:
  instance:
    prefer-ip-address: true


  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082

# One To Many on Hotel side
# Many To One on Subscription side